name: term_glyph
version: 1.2.0-nullsafety.2

description: Useful Unicode glyphs and ASCII substitutes.
homepage: https://github.com/dart-lang/term_glyph

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.12.0'

dev_dependencies:
  csv: '>=3.0.0 <5.0.0'
  dart_style: '>=0.2.0 <2.0.0'
  test: ^1.16.0-nullsafety
